import os
import re
import secrets
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from urllib.parse import urlparse

import httpx
import platformdirs

# Explicit fallback for the two real-world locations `docker` (and any
# other GUI-invoked CLI tool) commonly lives in but that a GUI launch's
# minimal launchd PATH doesn't include — Docker Desktop's own CLI
# symlink (/usr/local/bin) and Apple Silicon Homebrew (/opt/homebrew/
# bin). path_helper below already covers /usr/local/bin (it's always
# in /etc/paths) and often covers /opt/homebrew/bin too (when a real
# /etc/paths.d/homebrew file exists), but that file isn't guaranteed on
# every Homebrew install — Homebrew's own installer instructions rely
# on a shell-profile `eval "$(brew shellenv)"` instead, which a GUI
# launch never runs. Listed explicitly so detection doesn't silently
# depend on that file happening to exist.
_FALLBACK_BIN_DIRS = ("/opt/homebrew/bin", "/usr/local/bin")


def ensure_full_path_environment() -> None:
    """Extend os.environ["PATH"] to match what a real login/interactive
    shell would have, not the minimal PATH a GUI-launched macOS app
    actually gets.

    Root cause (item 44, confirmed live via a real ephemeral
    LaunchAgent probe — a genuine launchd-spawned process with no
    shell in the chain, the same path a double-clicked .app takes):
    a GUI launch's PATH is launchd's bare default,
    `/usr/bin:/bin:/usr/sbin:/sbin` — it does NOT include
    /usr/local/bin or /opt/homebrew/bin, since those are added by
    `/usr/libexec/path_helper` reading /etc/paths + /etc/paths.d/*,
    which only runs as part of a login shell's startup (/etc/zprofile
    et al.), never as part of a GUI app launch. `uv run seeker-ui`
    never hits this, since a terminal shell's PATH is already fully
    resolved by the time it inherits it — the same "works via uv run,
    breaks via a real double-click" shape as item 43's CWD bug, just
    for PATH instead of CWD. Called once at Application startup,
    before anything Docker-related runs, rather than patched into each
    individual subprocess.run(["docker", ...]) call site — every
    docker_setup.py call already passes env=None (inherit) or
    `{**os.environ, ...}`, so mutating the process's own os.environ
    here fixes every current and future call site at once.
    """
    try:
        result = subprocess.run(
            ["/usr/libexec/path_helper", "-s"],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
        match = re.search(r'PATH="([^"]*)"', result.stdout)
        resolved_path = match.group(1) if match else ""
    except Exception:
        # Best-effort only — this runs unconditionally at Application
        # startup (see the call site), so it must never be able to
        # crash startup itself, on any platform, for any reason
        # (path_helper doesn't exist at all outside macOS, and its
        # output shape isn't a contract this code controls). The
        # explicit _FALLBACK_BIN_DIRS below still get applied even
        # when this fails entirely.
        resolved_path = ""

    entries = resolved_path.split(":") if resolved_path else []
    entries += os.environ.get("PATH", "").split(":")
    entries += list(_FALLBACK_BIN_DIRS)

    merged = [entry for entry in dict.fromkeys(entries) if entry]
    os.environ["PATH"] = os.pathsep.join(merged)


def compose_file_path() -> Path:
    # Same reasoning/home as slskd_data_dir() just above: both
    # wizard.py and settings_window.py need the identical path, so it
    # lives here rather than being duplicated or imported UI-to-UI.
    #
    # docker-compose.yml is real *resource data*, not application code
    # — a packaged build (see packaging/seeker.spec) bundles it as a
    # PyInstaller `datas` entry. In an ordinary `uv run seeker-ui` dev
    # run, `sys.frozen` is never set, so this falls through to the same
    # CWD-relative path as before — `docker compose up` is documented
    # (README) to run from the project root, the same assumption
    # LEGACY_DATABASE_PATH made elsewhere before item 18. Deliberately
    # NOT source-tree-relative (e.g. via `__file__`) for the dev-mode
    # branch — that would be a real behavior change from what's shipped
    # and tested today, not just a packaging-mode addition.
    if not getattr(sys, "frozen", False):
        return Path("docker-compose.yml")

    # Roadmap item 74 (P5.3) — a frozen build used to resolve this
    # straight to `sys._MEIPASS`, the bundle's own extracted resource
    # root. Real, live-confirmed problem: `SharingService.
    # is_self_managed()` compares the running container's real
    # `com.docker.compose.project.config_files` label (recorded once,
    # at bring-up) against THIS path — but `sys._MEIPASS` is
    # regenerated by PyInstaller on every build, so a rebuilt or
    # relocated `.app` could never again recognize a container it had
    # itself previously created as self-managed. Fixed the same way
    # item 18 stabilized the DB's location: copy the bundled resource,
    # once, into the same stable per-user `slskd_data_dir()` this app
    # already treats as its permanent home, and always return THAT
    # canonical path afterward — guarded (only copies if the canonical
    # copy doesn't already exist yet) so a later Sharing-added volume
    # line is never clobbered by a subsequent app update.
    canonical_path = slskd_data_dir() / "docker-compose.yml"

    if not canonical_path.exists():
        canonical_path.parent.mkdir(parents=True, exist_ok=True)
        bundled_path = (
            Path(sys._MEIPASS)  # type: ignore[attr-defined]
            / "docker-compose.yml"
        )
        shutil.copy2(bundled_path, canonical_path)

    return canonical_path


def slskd_data_dir() -> Path:
    # Moved here from ui/wizard.py (Step 8) so Settings' "Update SoulSeek
    # credentials" action can resolve the identical path without either
    # duplicating it or importing a UI module from a service-layer one.
    # Same per-user app-data directory the DB/config store live in.
    return Path(
        platformdirs.user_data_dir("Seeker", appauthor=False)
    ) / "slskd-data"


class DockerState(Enum):
    NOT_INSTALLED = "not_installed"
    INSTALLED_NOT_RUNNING = "installed_not_running"
    RUNNING = "running"


def detect_docker_state() -> DockerState:
    try:
        subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            timeout=5,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return DockerState.NOT_INSTALLED
    except subprocess.TimeoutExpired:
        return DockerState.INSTALLED_NOT_RUNNING

    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            timeout=10,
            check=False,  # caller inspects result.returncode itself
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return DockerState.INSTALLED_NOT_RUNNING

    if result.returncode == 0:
        return DockerState.RUNNING

    return DockerState.INSTALLED_NOT_RUNNING


_LOOPBACK_HOSTS = {"localhost", "127.0.0.1", "::1"}


def is_non_loopback_http_url(url: str) -> bool:
    """True when `url` is plain (unencrypted) HTTP pointed somewhere
    other than this machine.

    Roadmap item 116 (round 8, §6.6.1) — `SoulseekClient` sends
    `X-API-Key` as a plain header on every request; over loopback
    that's fine, but a `SLSKD_BASE_URL` pointed at a remote host over
    `http://` would put the key on the wire in clear. Used to warn in
    Settings, not to block anything — this project already has no
    remote-slskd flow of its own, but `.env`'s `SLSKD_BASE_URL` is
    still user-editable outside the app.
    """
    parsed = urlparse(url)
    return parsed.scheme == "http" and parsed.hostname not in _LOOPBACK_HOSTS


def generate_api_key() -> str:
    # slskd documents API keys as 16-255 characters (see slskd.yml's own
    # example comment) — token_urlsafe(32) produces a 43-character
    # string, comfortably inside that range.
    return secrets.token_urlsafe(32)


# Real, confirmed-live env var names (2026-08-28) — read straight from
# the slskd binary's own `--envars` output against the actual running
# container, not assumed from docs. Two real, distinguishable
# credential pairs exist and are easy to conflate:
#   SLSKD_USERNAME / SLSKD_PASSWORD       -> the WEB UI login
#     (--help: "username/password for web UI", default "slskd"/"slskd")
#   SLSKD_SLSK_USERNAME / SLSKD_SLSK_PASSWORD -> the SOULSEEK NETWORK
#     login (--help: "username/password for the Soulseek network").
# Confirmed empirically which is which by starting a throwaway
# container with each candidate pair and reading its own logs: setting
# SLSKD_SOULSEEK_USERNAME/PASSWORD (a plausible-looking but WRONG
# guess) and bare SLSKD_USERNAME/PASSWORD both produced "Not connecting
# to the Soulseek server; username and/or password invalid"; only
# SLSKD_SLSK_USERNAME/SLSKD_SLSK_PASSWORD produced a real
# "Logged in to the Soulseek server as <username>" — this wizard's
# credential fields map to these two, and only these two.
SLSKD_NETWORK_USERNAME_ENV_VAR = "SLSKD_SLSK_USERNAME"
SLSKD_NETWORK_PASSWORD_ENV_VAR = "SLSKD_SLSK_PASSWORD"

# Roadmap item 116 (round 8, §6.1.2) — the WEB UI pair the comment
# directly above already named, now actually used: `bring_up_slskd`
# passed neither before this item, leaving the web UI at slskd's own
# vendor default ("slskd"/"slskd").
SLSKD_WEB_USERNAME_ENV_VAR = "SLSKD_USERNAME"
SLSKD_WEB_PASSWORD_ENV_VAR = "SLSKD_PASSWORD"


SLSKD_HEALTHY_STATE = "Connected, LoggedIn"

# Real, confirmed-live finding (2026-08-28): slskd's /api/v0/server (and
# /api/v0/application's "server" block) never distinguishes "still
# negotiating" from "rejected — bad credentials" — its ServerState
# schema (confirmed via the live swagger spec) carries only
# state/isConnected/isLoggedIn/isTransitioning, no error/reason field
# at all. Both a genuine bad-password rejection and an unrelated
# "kicked, another client already logged in with this username" case
# were observed live to converge on the exact same terminal
# state: "Disconnected". The real reason only ever appears via
# /api/v0/logs' Error-level entries — confirmed live for a deliberately
# wrong password: "Disconnected from the Soulseek server: invalid
# username or password" / "Failed to reconnect: ...INVALIDPASS".
#
# Checked for a more structured signal before settling on substring
# matching, not assumed to be the only option: a real captured entry's
# full shape is {timestamp, context, level, message} — "context" is
# real ("slskd.Application") but too coarse to discriminate a
# credential rejection from any other application-level error, so it
# narrows nothing beyond level=="Error" (already checked separately in
# check_slskd_health). Message-substring matching against these two
# confirmed real strings is genuinely the most specific signal
# available, not a shortcut taken over a better one. Matched
# case-insensitively, same discipline as RECOGNIZED_REJECTION_PATTERNS
# elsewhere in this codebase — not broadened past what's actually been
# confirmed. A future slskd version could still reword these messages;
# there's no structured error-code field to pin to instead, so this
# stays worth re-checking against a real container after any slskd
# upgrade.
BAD_CREDENTIALS_LOG_PATTERNS = ("invalid username or password", "invalidpass")

# Roadmap item 8 — the third real state item 23's own comment above
# already flagged as observed-but-unclassified. Confirmed live
# (2026-08-31) via two genuinely disposable, throwaway slskd containers
# (never the real production one — see docs/HISTORY.md item 8 for the
# full setup): logging a second client in with the SAME real,
# already-connected username produces a real, distinct Error-level log
# line — "Disconnected from the Soulseek server: another client logged
# in using the same username" — preceded by an Information-level
# "Kicked from server." This substring is genuinely disjoint from
# BAD_CREDENTIALS_LOG_PATTERNS above (no shared words), so checking it
# first or after makes no difference to correctness.
KICKED_LOG_PATTERNS = ("another client logged in using the same username",)


class SlskdHealthStatus(Enum):
    HEALTHY = "healthy"
    BAD_CREDENTIALS = "bad_credentials"
    KICKED = "kicked"
    NOT_READY = "not_ready"


@dataclass
class SlskdHealthCheckResult:
    status: SlskdHealthStatus
    detail: str | None = None


def _parse_log_timestamp(raw: object) -> datetime | None:
    if not isinstance(raw, str):
        return None

    try:
        return datetime.fromisoformat(raw)
    except ValueError:
        return None


def check_slskd_health(
        base_url: str,
        api_key: str,
        since: datetime,
) -> SlskdHealthCheckResult:
    # A single check, not a blocking poll loop — the wizard's own QTimer
    # calls this repeatedly (same pattern as the dashboard's live-status
    # poll), tracking overall elapsed time itself for the timeout. Keeps
    # this directly, deterministically testable per call.
    #
    # `since` (the real timestamp this specific bring-up attempt
    # started, captured by the caller) matters because /api/v0/logs
    # returns the whole recent log buffer, not just what happened after
    # this call — without filtering, a stale Error entry from an
    # earlier attempt (e.g. the user mistyped their password once,
    # corrected it, and the wizard retried) would false-positive every
    # later poll as BAD_CREDENTIALS forever, even after a real
    # successful reconnect.
    headers = {"X-API-Key": api_key}

    try:
        response = httpx.get(
            f"{base_url}/api/v0/application", headers=headers, timeout=10.0,
        )
        response.raise_for_status()
        state = response.json().get("server", {}).get("state")

        if state == SLSKD_HEALTHY_STATE:
            return SlskdHealthCheckResult(SlskdHealthStatus.HEALTHY)
    except httpx.HTTPError:
        return SlskdHealthCheckResult(SlskdHealthStatus.NOT_READY)

    try:
        logs_response = httpx.get(
            f"{base_url}/api/v0/logs", headers=headers, timeout=10.0,
        )
        logs_response.raise_for_status()

        for entry in logs_response.json():
            if entry.get("level") != "Error":
                continue

            entry_timestamp = _parse_log_timestamp(entry.get("timestamp"))

            # An entry with no parseable timestamp can't be proven
            # recent — skip rather than risk a false positive from
            # something stale.
            if entry_timestamp is None or entry_timestamp < since:
                continue

            message = str(entry.get("message", "")).lower()

            if any(
                    pattern in message
                    for pattern in BAD_CREDENTIALS_LOG_PATTERNS
            ):
                return SlskdHealthCheckResult(
                    SlskdHealthStatus.BAD_CREDENTIALS,
                    detail=str(entry.get("message")),
                )

            if any(
                    pattern in message
                    for pattern in KICKED_LOG_PATTERNS
            ):
                return SlskdHealthCheckResult(
                    SlskdHealthStatus.KICKED,
                    detail=str(entry.get("message")),
                )
    except httpx.HTTPError:
        pass

    return SlskdHealthCheckResult(SlskdHealthStatus.NOT_READY)


class SlskdWebLoginStatus(Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    UNKNOWN = "unknown"


def check_slskd_web_login(
        base_url: str,
        username: str,
        password: str,
) -> SlskdWebLoginStatus:
    """Confirm a WEB UI login (distinct from the API-key-authenticated
    calls everywhere else in this codebase) actually works against the
    real running container, by attempting the same
    `POST /api/v0/session` slskd's own login page uses.

    Roadmap item 116/S1.2 — `ensure_slskd_web_credentials()` generates
    and persists a login, but slskd will not let `SLSKD_USERNAME`/
    `SLSKD_PASSWORD` override a web UI login that was already
    customised before Seeker ever set the env var — the persisted
    value can silently stop matching what the container will actually
    accept. Live-confirmed against a real running production
    container: a generated credential that didn't take produces a
    real `401`, not an error. `UNKNOWN` covers slskd being unreachable
    at all (caller should not claim a login is broken when it simply
    couldn't be checked).
    """
    try:
        response = httpx.post(
            f"{base_url}/api/v0/session",
            json={"username": username, "password": password},
            timeout=10.0,
        )
    except httpx.HTTPError:
        return SlskdWebLoginStatus.UNKNOWN

    if response.status_code == 200:
        return SlskdWebLoginStatus.ACTIVE

    if response.status_code == 401:
        return SlskdWebLoginStatus.INACTIVE

    return SlskdWebLoginStatus.UNKNOWN


def bring_up_slskd(
        compose_file: str,
        soulseek_username: str,
        soulseek_password: str,
        api_key: str,
        slskd_data_dir: str,
        web_username: str,
        web_password: str,
        library_location_path: str | None = None,
) -> subprocess.CompletedProcess[str]:
    # Passes the collected credentials/API key/paths directly as
    # environment variables to `docker compose up`, which Compose
    # substitutes into docker-compose.yml's ${VAR} placeholders — no
    # second, compose-specific env file (matches how Task 1 already
    # rejected a second .env-editing mechanism for this exact reason).
    #
    # `library_location_path` is optional (roadmap item R6) — a
    # recreate triggered by SharingService.add_location_to_share
    # already knows the CURRENT live-mounted original share path (or
    # genuinely doesn't, if that mount is somehow gone) and must not
    # clobber it with a blank; omitting the key entirely lets Compose
    # fall through to docker-compose.yml's own `${SLSKD_SHARE_PATH:-...}`
    # default instead of substituting an explicit empty string, same
    # reasoning as R6's own root-cause diagnosis for SLSKD_API_KEY.
    env = {
        **os.environ,
        SLSKD_NETWORK_USERNAME_ENV_VAR: soulseek_username,
        SLSKD_NETWORK_PASSWORD_ENV_VAR: soulseek_password,
        "SLSKD_API_KEY": api_key,
        "SLSKD_DATA_DIR": slskd_data_dir,
        SLSKD_WEB_USERNAME_ENV_VAR: web_username,
        SLSKD_WEB_PASSWORD_ENV_VAR: web_password,
    }

    if library_location_path is not None:
        env["SLSKD_SHARE_PATH"] = library_location_path

    return subprocess.run(
        ["docker", "compose", "-f", compose_file, "up", "-d"],
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,  # caller inspects .returncode itself
    )
